// @generated - mapa de iconos Lucide importados explícitamente (tree-shakeable)

import {
  ArrowDown as LucideArrowDown,
  ArrowUp as LucideArrowUp,
  BadgeQuestionMark as LucideBadgeQuestionMark,
  Bed as LucideBed,
  Beer as LucideBeer,
  Book as LucideBook,
  Box as LucideBox,
  Briefcase as LucideBriefcase,
  Bus as LucideBus,
  Calculator as LucideCalculator,
  Calendar as LucideCalendar,
  Camera as LucideCamera,
  Car as LucideCar,
  ChartColumn as LucideChartColumn,
  Check as LucideCheck,
  ChevronDown as LucideChevronDown,
  ChevronLeft as LucideChevronLeft,
  ChevronRight as LucideChevronRight,
  ChevronUp as LucideChevronUp,
  CircleAlert as LucideCircleAlert,
  CircleArrowDown as LucideCircleArrowDown,
  CircleArrowUp as LucideCircleArrowUp,
  CircleCheck as LucideCircleCheck,
  CircleDollarSign as LucideCircleDollarSign,
  CircleUser as LucideCircleUser,
  CircleX as LucideCircleX,
  Clapperboard as LucideClapperboard,
  Clock as LucideClock,
  Cloud as LucideCloud,
  Code as LucideCode,
  Copy as LucideCopy,
  CreditCard as LucideCreditCard,
  Droplets as LucideDroplets,
  Dumbbell as LucideDumbbell,
  Ear as LucideEar,
  Ellipsis as LucideEllipsis,
  ExternalLink as LucideExternalLink,
  Eye as LucideEye,
  EyeOff as LucideEyeOff,
  FaceGrinning as LucideFaceGrinning,
  FaceSlightlyFrowning as LucideFaceSlightlyFrowning,
  Folder as LucideFolder,
  FolderOpen as LucideFolderOpen,
  Gamepad2 as LucideGamepad2,
  Gift as LucideGift,
  Glasses as LucideGlasses,
  Globe as LucideGlobe,
  GraduationCap as LucideGraduationCap,
  Hammer as LucideHammer,
  Heart as LucideHeart,
  House as LucideHouse,
  IceCreamCone as LucideIceCreamCone,
  Image as LucideImage,
  Info as LucideInfo,
  Key as LucideKey,
  Languages as LucideLanguages,
  Laptop as LucideLaptop,
  Layers as LucideLayers,
  LayoutDashboard as LucideLayoutDashboard,
  Leaf as LucideLeaf,
  Lightbulb as LucideLightbulb,
  Link as LucideLink,
  List as LucideList,
  LogOut as LucideLogOut,
  Mail as LucideMail,
  Map as LucideMap,
  Megaphone as LucideMegaphone,
  Mic as LucideMic,
  Moon as LucideMoon,
  Move as LucideMove,
  Navigation as LucideNavigation,
  PawPrint as LucidePawPrint,
  Pencil as LucidePencil,
  Pizza as LucidePizza,
  Printer as LucidePrinter,
  RefreshCw as LucideRefreshCw,
  Scissors as LucideScissors,
  Search as LucideSearch,
  Send as LucideSend,
  Settings as LucideSettings,
  Share2 as LucideShare2,
  Shield as LucideShield,
  Shirt as LucideShirt,
  ShoppingBag as LucideShoppingBag,
  ShoppingBasket as LucideShoppingBasket,
  Smartphone as LucideSmartphone,
  Snowflake as LucideSnowflake,
  Square as LucideSquare,
  Star as LucideStar,
  Stethoscope as LucideStethoscope,
  Store as LucideStore,
  Sun as LucideSun,
  Tag as LucideTag,
  Telescope as LucideTelescope,
  Timer as LucideTimer,
  TrainFront as LucideTrainFront,
  Trash2 as LucideTrash2,
  TrendingDown as LucideTrendingDown,
  TrendingUp as LucideTrendingUp,
  Triangle as LucideTriangle,
  Umbrella as LucideUmbrella,
  User as LucideUser,
  Utensils as LucideUtensils,
  UtensilsCrossed as LucideUtensilsCrossed,
  Video as LucideVideo,
  Volume2 as LucideVolume2,
  Wallet as LucideWallet,
  Watch as LucideWatch,
  Wifi as LucideWifi,
  X as LucideX,
  Zap as LucideZap} from "lucide-react-native";

type IconComponent = React.ComponentType<{ size?: number; color?: string; strokeWidth?: number }>;

const ICON_MAP: Record<string, IconComponent> = {
  "ArrowDown": LucideArrowDown,
  "ArrowUp": LucideArrowUp,
  "BadgeQuestionMark": LucideBadgeQuestionMark,
  "Bed": LucideBed,
  "Beer": LucideBeer,
  "Book": LucideBook,
  "Box": LucideBox,
  "Briefcase": LucideBriefcase,
  "Bus": LucideBus,
  "Calculator": LucideCalculator,
  "Calendar": LucideCalendar,
  "Camera": LucideCamera,
  "Car": LucideCar,
  "ChartColumn": LucideChartColumn,
  "Check": LucideCheck,
  "ChevronDown": LucideChevronDown,
  "ChevronLeft": LucideChevronLeft,
  "ChevronRight": LucideChevronRight,
  "ChevronUp": LucideChevronUp,
  "CircleAlert": LucideCircleAlert,
  "CircleArrowDown": LucideCircleArrowDown,
  "CircleArrowUp": LucideCircleArrowUp,
  "CircleCheck": LucideCircleCheck,
  "CircleDollarSign": LucideCircleDollarSign,
  "CircleUser": LucideCircleUser,
  "CircleX": LucideCircleX,
  "Clapperboard": LucideClapperboard,
  "Clock": LucideClock,
  "Cloud": LucideCloud,
  "Code": LucideCode,
  "Copy": LucideCopy,
  "CreditCard": LucideCreditCard,
  "Droplets": LucideDroplets,
  "Dumbbell": LucideDumbbell,
  "Ear": LucideEar,
  "Ellipsis": LucideEllipsis,
  "ExternalLink": LucideExternalLink,
  "Eye": LucideEye,
  "EyeOff": LucideEyeOff,
  "FaceGrinning": LucideFaceGrinning,
  "FaceSlightlyFrowning": LucideFaceSlightlyFrowning,
  "Folder": LucideFolder,
  "FolderOpen": LucideFolderOpen,
  "Gamepad2": LucideGamepad2,
  "Gift": LucideGift,
  "Glasses": LucideGlasses,
  "Globe": LucideGlobe,
  "GraduationCap": LucideGraduationCap,
  "Hammer": LucideHammer,
  "Heart": LucideHeart,
  "House": LucideHouse,
  "IceCreamCone": LucideIceCreamCone,
  "Image": LucideImage,
  "Info": LucideInfo,
  "Key": LucideKey,
  "Languages": LucideLanguages,
  "Laptop": LucideLaptop,
  "Layers": LucideLayers,
  "LayoutDashboard": LucideLayoutDashboard,
  "Leaf": LucideLeaf,
  "Lightbulb": LucideLightbulb,
  "Link": LucideLink,
  "List": LucideList,
  "LogOut": LucideLogOut,
  "Mail": LucideMail,
  "Map": LucideMap,
  "Megaphone": LucideMegaphone,
  "Mic": LucideMic,
  "Moon": LucideMoon,
  "Move": LucideMove,
  "Navigation": LucideNavigation,
  "PawPrint": LucidePawPrint,
  "Pencil": LucidePencil,
  "Pizza": LucidePizza,
  "Printer": LucidePrinter,
  "RefreshCw": LucideRefreshCw,
  "Scissors": LucideScissors,
  "Search": LucideSearch,
  "Send": LucideSend,
  "Settings": LucideSettings,
  "Share2": LucideShare2,
  "Shield": LucideShield,
  "Shirt": LucideShirt,
  "ShoppingBag": LucideShoppingBag,
  "ShoppingBasket": LucideShoppingBasket,
  "Smartphone": LucideSmartphone,
  "Snowflake": LucideSnowflake,
  "Square": LucideSquare,
  "Star": LucideStar,
  "Stethoscope": LucideStethoscope,
  "Store": LucideStore,
  "Sun": LucideSun,
  "Tag": LucideTag,
  "Telescope": LucideTelescope,
  "Timer": LucideTimer,
  "TrainFront": LucideTrainFront,
  "Trash2": LucideTrash2,
  "TrendingDown": LucideTrendingDown,
  "TrendingUp": LucideTrendingUp,
  "Triangle": LucideTriangle,
  "Umbrella": LucideUmbrella,
  "User": LucideUser,
  "Utensils": LucideUtensils,
  "UtensilsCrossed": LucideUtensilsCrossed,
  "Video": LucideVideo,
  "Volume2": LucideVolume2,
  "Wallet": LucideWallet,
  "Watch": LucideWatch,
  "Wifi": LucideWifi,
  "X": LucideX,
  "Zap": LucideZap};

const FALLBACK: keyof typeof ICON_MAP = "Wallet";

const LEGACY_MAP: Record<string, keyof typeof ICON_MAP> = {
  restaurant: "Utensils",
  car: "Car",
  medical: "Stethoscope",
  home: "House",
  flash: "Zap",
  school: "GraduationCap",
  shirt: "Shirt",
  film: "Clapperboard",
  barbell: "Dumbbell",
  paw: "PawPrint",
  card: "CreditCard",
  wifi: "Wifi",
  "phone-portrait": "Smartphone",
  book: "Book",
  fitness: "Dumbbell",
  "game-controller": "Gamepad2",
  heart: "Heart",
  leaf: "Leaf",
  water: "Droplets",
  cloud: "Cloud",
  camera: "Camera",
  briefcase: "Briefcase",
  storefront: "Store",
  "trending-up": "TrendingUp",
  key: "Key",
  gift: "Gift",
  pizza: "Pizza",
  beer: "Beer",
  "ice-cream": "IceCreamCone",
  happy: "FaceGrinning",
  sad: "FaceSlightlyFrowning",
  wallet: "Wallet",
  bag: "ShoppingBag",
  basket: "ShoppingBasket",
  bed: "Bed",
  bulb: "Lightbulb",
  bus: "Bus",
  calculator: "Calculator",
  checkmark: "Check",
  close: "X",
  cube: "Box",
  cut: "Scissors",
  duplicate: "Copy",
  ear: "Ear",
  eye: "Eye",
  "fast-food": "UtensilsCrossed",
  folder: "Folder",
  glasses: "Glasses",
  globe: "Globe",
  hammer: "Hammer",
  "home-outline": "House",
  image: "Image",
  information: "Info",
  language: "Languages",
  laptop: "Laptop",
  layers: "Layers",
  link: "Link",
  list: "List",
  mail: "Mail",
  map: "Map",
  megaphone: "Megaphone",
  mic: "Mic",
  moon: "Moon",
  move: "Move",
  navigate: "Navigation",
  open: "ExternalLink",
  pricetag: "Tag",
  print: "Printer",
  search: "Search",
  settings: "Settings",
  share: "Share2",
  shield: "Shield",
  snow: "Snowflake",
  star: "Star",
  stop: "Square",
  sunny: "Sun",
  telescope: "Telescope",
  timer: "Timer",
  train: "TrainFront",
  trash: "Trash2",
  "trending-down": "TrendingDown",
  triangle: "Triangle",
  umbrella: "Umbrella",
  videocam: "Video",
  "volume-high": "Volume2",
  watch: "Watch",
  "checkmark-circle": "CircleCheck",
  "close-circle": "CircleX",
  "alert-circle": "CircleAlert",
  "information-circle": "Info",
  refresh: "RefreshCw"
};

export function resolveLucideName(
  name?: string | null,
): keyof typeof ICON_MAP {
  if (!name) return FALLBACK;
  if (name in ICON_MAP) return name as keyof typeof ICON_MAP;
  const legacy = LEGACY_MAP[name];
  if (legacy) return legacy;
  return FALLBACK;
}

type LucideIconProps = {
  name?: string | null;
  size?: number;
  color?: string;
  strokeWidth?: number;
};

export function LucideIcon({
  name,
  size = 24,
  color = "#000",
  strokeWidth = 2,
}: LucideIconProps) {
  const resolved = resolveLucideName(name);
  const Component = ICON_MAP[resolved];
  return <Component size={size} color={color} strokeWidth={strokeWidth} />;
}
